server:
  port: ${PORT:8090}
  servlet:
    context-path: /api


spring:
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    # show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/krystal-distribution-group/protocol/openid-connect/certs
          issuer-uri: http://localhost:8180/realms/krystal-distribution-group
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/app_db}
    username: ${DATASOURCE_USER:user}
    password: ${DATASOURCE_PASS:password}
    initialize: true
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword
logging:
  level:
    sql: debug
